define ORADATA_PATH = D:\oracle\oradata\wechat;
--define ORADATA_PATH = /oracle/oradata/wechat;
--define ORADATA_PATH = /oradata;

--用户默认表空间
DROP TABLESPACE USERS INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE USERS DATAFILE 
'&ORADATA_PATH/users.dbf' 
SIZE 100M
AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;


--创建用户
Create user wechat identified by wechat default tablespace USERS;
Grant connect,resource to wechat;
Grant dba to wechat;


--wechat tablespace
DROP TABLESPACE WECHAT_SPACE INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE WECHAT_SPACE DATAFILE 
'&ORADATA_PATH/wechat_space.dbf' 
SIZE 300M
AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

--partition
DROP TABLESPACE WECHAT_ADDCLEAR_NOTES_SPACE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;
DROP TABLESPACE WECHAT_TRANS_DATA_SPACE INCLUDING CONTENTS AND DATAFILES CASCADE CONSTRAINTS;

CREATE TABLESPACE WECHAT_ADDCLEAR_NOTES_SPACE DATAFILE 
  '&ORADATA_PATH/WECHAT_ADDCLEAR_NOTES_SPACE_PART1.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED,
  '&ORADATA_PATH/WECHAT_ADDCLEAR_NOTES_SPACE_PART2.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED,
  '&ORADATA_PATH/WECHAT_ADDCLEAR_NOTES_SPACE_PART3.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED,
  '&ORADATA_PATH/WECHAT_ADDCLEAR_NOTES_SPACE_PART4.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

CREATE TABLESPACE WECHAT_TRANS_DATA_SPACE DATAFILE 
  '&ORADATA_PATH/WECHAT_TRANS_DATA_SPACE_PART1.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED,
  '&ORADATA_PATH/WECHAT_TRANS_DATA_SPACE_PART2.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED,
  '&ORADATA_PATH/WECHAT_TRANS_DATA_SPACE_PART3.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED,
  '&ORADATA_PATH/WECHAT_TRANS_DATA_SPACE_PART4.dbf' SIZE 64M AUTOEXTEND ON NEXT 64M MAXSIZE UNLIMITED
LOGGING ONLINE PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE BLOCKSIZE 8K SEGMENT SPACE MANAGEMENT AUTO FLASHBACK ON;

--history tablespace
DROP TABLESPACE HISTSPACE INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE HISTSPACE DATAFILE 
'&ORADATA_PATH/histspace.dbf' 
SIZE 300M
AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

--log tablespace
DROP TABLESPACE LOGSPACE INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE LOGSPACE DATAFILE 
'&ORADATA_PATH/logspace.dbf' 
SIZE 100M
AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

--index_primary tablespace
DROP TABLESPACE IDXPRIMARY INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE IDXPRIMARY DATAFILE 
'&ORADATA_PATH/IDXPRIMARY.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;

--index_second tablespace
DROP TABLESPACE IDXSECOND INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE IDXSECOND DATAFILE 
'&ORADATA_PATH/IDXSECOND.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 5120K MAXSIZE UNLIMITED
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
