<input type="hidden" id="script.IntervelError" value="<%=resource.srcStr("script.IntervelError")%>" />
<input type="hidden" id="script.adsForSinglePreview.validFile" value="<%=resource.srcStr("script.adsForSinglePreview.validFile")%>" />
<input type="hidden" id="script.adsStartTimeEndTime" value="<%=resource.srcStr("script.adsStartTimeEndTime")%>" />
<input type="hidden" id="script.adsTimeInputError" value="<%=resource.srcStr("script.adsTimeInputError")%>" />
<input type="hidden" id="script.adsForSinglePreview.adsDev" value="<%=resource.srcStr("script.adsForSinglePreview.adsDev")%>" />
<input type="hidden" id="script.adsForSinglePreview.noPreview" value="<%=resource.srcStr("script.adsForSinglePreview.noPreview")%>" />
<input type="hidden" id="script.adsForSinglePreview.accessoryLimit" value="<%=resource.srcStr("script.adsForSinglePreview.accessoryLimit")%>" />
<input type="hidden" id="script.adsForSinglePreview.tradeCode" value="<%=resource.srcStr("script.adsForSinglePreview.tradeCode")%>" />
<input type="hidden" id="Main.delete" value="<%=resource.srcStr("Main.delete")%>" />
<input type="hidden" id="script.accessory" value="<%=resource.srcStr("script.accessory")%>" />
<input type="hidden" id="script.playTime" value="<%=resource.srcStr("script.playTime")%>" />
<input type="hidden" id="script.adsForSinglePreview.timeDivision" value="<%=resource.srcStr("script.adsForSinglePreview.timeDivision")%>" />
<input type="hidden" id="Main.begin_time" value="<%=resource.srcStr("Main.begin_time")%>" />
<input type="hidden" id="Main.hour" value="<%=resource.srcStr("Main.hour")%>" />
<input type="hidden" id="Main.min" value="<%=resource.srcStr("Main.min")%>" />
<input type="hidden" id="Main.sec" value="<%=resource.srcStr("Main.sec")%>" />
<input type="hidden" id="script.stopTime" value="<%=resource.srcStr("script.stopTime")%>" />
<input type="hidden" id="script.adsForSinglePreview.advType" value="<%=resource.srcStr("script.adsForSinglePreview.advType")%>" />
<input type="hidden" id="script.canNotDecrease" value="<%=resource.srcStr("script.canNotDecrease")%>" />
<input type="hidden" id="script.adsForSinglePreview.validValue" value="<%=resource.srcStr("script.adsForSinglePreview.validValue")%>" />
<input type="hidden" id="script.inputPlayTimeError" value="<%=resource.srcStr("script.inputPlayTimeError")%>" />
<input type="hidden" id="script.adsForSinglePreview.noAccessory" value="<%=resource.srcStr("script.adsForSinglePreview.noAccessory")%>" />
<input type="hidden" id="script.adsForSinglePreview.wait" value="<%=resource.srcStr("script.adsForSinglePreview.wait")%>" />
<input type="hidden" id="script.adsForSinglePreview.addOnly" value="<%=resource.srcStr("script.adsForSinglePreview.addOnly")%>" />
<input type="hidden" id="script.adsForSinglePreview.fileQuantity" value="<%=resource.srcStr("script.adsForSinglePreview.fileQuantity")%>" />
