<input type="hidden" id="script.docFileView.selectDev" value="<%=resource.srcStr("script.docFileView.selectDev") %>" />
<input type="hidden" id="script.docFileView.alreadyHight" value="<%=resource.srcStr("script.docFileView.alreadyHight") %>" />
<input type="hidden" id="script.docFileView.clickUpper" value="<%=resource.srcStr("script.docFileView.clickUpper") %>" />
<input type="hidden" id="script.docFileView.clickRefresh" value="<%=resource.srcStr("script.docFileView.clickRefresh") %>" />
<input type="hidden" id="script.common.oprateLater" value="<%=resource.srcStr("script.common.oprateLater") %>" />
<input type="hidden" id="script.docFileView.delFile" value="<%=resource.srcStr("script.docFileView.delFile") %>" />
<input type="hidden" id="script.docFileView.statisticOperate" value="<%=resource.srcStr("script.docFileView.statisticOperate") %>" />
<input type="hidden" id="script.docFileView.cannotUpload" value="<%=resource.srcStr("script.docFileView.cannotUpload") %>" />
<input type="hidden" id="script.docFileView.confirm" value="<%=resource.srcStr("script.docFileView.confirm") %>" />
<input type="hidden" id="script.docFileView.uploadCancel" value="<%=resource.srcStr("script.docFileView.uploadCancel") %>" />
<input type="hidden" id="script.docFileView.excuteFile" value="<%=resource.srcStr("script.docFileView.excuteFile") %>" />
<input type="hidden" id="script.docFileView.excuteConfirm" value="<%=resource.srcStr("script.docFileView.excuteConfirm") %>" />
<input type="hidden" id="control.atmFunctionDetail.dev" value="<%=resource.srcStr("control.atmFunctionDetail.dev") %>" />
<input type="hidden" id="control.devMonitor.questionMark" value="<%=resource.srcStr("control.devMonitor.questionMark") %>" />