<input type="hidden" id="script.singlefileads.limitPrompt" value="<%=resource.srcStr("script.singlefileads.limitPrompt") %>" />
<input type="hidden" id="Main.begin_time" value="<%=resource.srcStr("Main.begin_time") %>" />
<input type="hidden" id="Main.hour" value="<%=resource.srcStr("Main.hour") %>" />
<input type="hidden" id="Main.min" value="<%=resource.srcStr("Main.min") %>" />
<input type="hidden" id="Main.sec" value="<%=resource.srcStr("Main.sec") %>" />
<input type="hidden" id="Main.end_time" value="<%=resource.srcStr("Main.end_time") %>" />
<input type="hidden" id="script.singlefileads.delTime" value="<%=resource.srcStr("script.singlefileads.delTime") %>" />
<input type="hidden" id="script.singlefileads.addTime" value="<%=resource.srcStr("script.singlefileads.addTime") %>" />
<input type="hidden" id="script.singlefileads.cannotDelAll" value="<%=resource.srcStr("script.singlefileads.cannotDelAll") %>" />
<input type="hidden" id="script.singlefileads.selectRight" value="<%=resource.srcStr("script.singlefileads.selectRight") %>" />
<input type="hidden" id="script.singlefileads.addFullAds" value="<%=resource.srcStr("script.singlefileads.addFullAds") %>" />
<input type="hidden" id="script.singlefileads.addtranceAds" value="<%=resource.srcStr("script.singlefileads.addtranceAds") %>" />
<input type="hidden" id="script.singlefileads.selectMedia" value="<%=resource.srcStr("script.singlefileads.selectMedia") %>" />
<input type="hidden" id="Version.notice_text" value="<%=resource.srcStr("Version.notice_text") %>" />
<input type="hidden" id="Version.announcement" value="<%=resource.srcStr("Version.announcement")%>" /> 
<input type="hidden" id="script.txtContent" value="<%=resource.srcStr("script.txtContent") %>" />
<input type="hidden" id="script.announcement" value="<%=resource.srcStr("script.announcement")%>" />
<input type="hidden" id="script.singlefileads.adsTime" value="<%=resource.srcStr("script.singlefileads.adsTime") %>" />
<input type="hidden" id="src.To" value="<%=resource.srcStr("src.To") %>" />
<input type="hidden" id="script.singlefileads.adsDuration" value="<%=resource.srcStr("script.singlefileads.adsDuration") %>" />
<input type="hidden" id="script.singlefileads.DurationLimit" value="<%=resource.srcStr("script.singlefileads.DurationLimit") %>" />
<input type="hidden" id="script.singlefileads.timeZone" value="<%=resource.srcStr("script.singlefileads.timeZone") %>" />
<input type="hidden" id="script.singlefileads.txtPreview" value="<%=resource.srcStr("script.singlefileads.txtPreview") %>" />
<input type="hidden" id="script.singlefileads.txtExample" value="<%=resource.srcStr("script.singlefileads.txtExample") %>" />
<input type="hidden" id="script.singlefileads.clickPreview" value="<%=resource.srcStr("script.singlefileads.clickPreview") %>" />
<input type="hidden" id="script.singlefileads.clickPath" value="<%=resource.srcStr("script.singlefileads.clickPath") %>" />
<input type="hidden" id="script.singlefileads.clickVideoPreview" value="<%=resource.srcStr("script.singlefileads.clickVideoPreview") %>" />
<input type="hidden" id="script.singlefileads.videoFilePath" value="<%=resource.srcStr("script.singlefileads.videoFilePath") %>" />
<input type="hidden" id="script.singlefileads.previewPic" value="<%=resource.srcStr("script.singlefileads.previewPic") %>" />
<input type="hidden" id="script.singlefileads.startTimeSelect" value="<%=resource.srcStr("script.singlefileads.startTimeSelect") %>" />
<input type="hidden" id="script.singlefileads.startTimeError" value="<%=resource.srcStr("script.singlefileads.startTimeError") %>" />
<input type="hidden" id="script.singlefileads.endTimeSelect" value="<%=resource.srcStr("script.singlefileads.endTimeSelect") %>" />
<input type="hidden" id="script.singlefileads.endTimeError" value="<%=resource.srcStr("script.singlefileads.endTimeError") %>" />
<input type="hidden" id="script.singlefileads.startEndTimeError" value="<%=resource.srcStr("script.singlefileads.startEndTimeError") %>" />
<input type="hidden" id="script.singlefileads.durationError" value="<%=resource.srcStr("script.singlefileads.durationError") %>" />
<input type="hidden" id="script.singlefileads.durationEmpty" value="<%=resource.srcStr("script.singlefileads.durationEmpty") %>" />
<input type="hidden" id="script.singlefileads.durationErrorPrompt" value="<%=resource.srcStr("script.singlefileads.durationErrorPrompt") %>" />
<input type="hidden" id="script.singlefileads.durationPrompt" value="<%=resource.srcStr("script.singlefileads.durationPrompt") %>" />
<input type="hidden" id="Main.the" value="<%=resource.srcStr("Main.the") %>" />
<input type="hidden" id="script.singlefileads.andDuration" value="<%=resource.srcStr("script.singlefileads.andDuration") %>" />
<input type="hidden" id="Main.sec" value="<%=resource.srcStr("Main.sec") %>" />
<input type="hidden" id="script.singlefileads.duration" value="<%=resource.srcStr("script.singlefileads.duration") %>" />
<input type="hidden" id="script.singlefileads.wrong" value="<%=resource.srcStr("script.singlefileads.wrong") %>" />
<input type="hidden" id="script.singlefileads.jpgaviSupport" value="<%=resource.srcStr("script.singlefileads.jpgaviSupport") %>" />
<input type="hidden" id="script.ads.playForever" value="<%=resource.srcStr("script.ads.playForever") %>" />