<input type="hidden" id="Version.time_adv" value="<%=resource.srcStr("Version.time_adv")%>" />        
<input type="hidden" id="script.ads.fileSelection" value="<%=resource.srcStr("script.ads.fileSelection")%>" />                
<input type="hidden" id="script.ads.atMost" value="<%=resource.srcStr("script.ads.atMost")%>" />                              
<input type="hidden" id="script.adsForSinglePreview.fileQuantity" value="<%=resource.srcStr("script.adsForSinglePreview.fileQuantity")%>" />                                  
<input type="hidden" id="script.ads.addFile" value="<%=resource.srcStr("script.ads.addFile")%>" />                            
<input type="hidden" id="script.ads.play" value="<%=resource.srcStr("script.ads.play")%>" />                                  
<input type="hidden" id="script.ads.addAccessory" value="<%=resource.srcStr("script.ads.addAccessory")%>" />                  
<input type="hidden" id="script.ads.delThis" value="<%=resource.srcStr("script.ads.delThis")%>" />                            
<input type="hidden" id="Version.delete_adv" value="<%=resource.srcStr("Version.delete_adv")%>" />                  
<input type="hidden" id="script.ads.preview" value="<%=resource.srcStr("script.ads.preview")%>" />                            
<input type="hidden" id="script.ads.simpleEffect" value="<%=resource.srcStr("script.ads.simpleEffect")%>" />                  
<input type="hidden" id="script.ads.timeSetting" value="<%=resource.srcStr("script.ads.timeSetting")%>" />                    
<input type="hidden" id="script.ads.playWay" value="<%=resource.srcStr("script.ads.playWay")%>" />                            
<input type="hidden" id="script.ads.playForever" value="<%=resource.srcStr("script.ads.playForever")%>" />                    
<input type="hidden" id="script.ads.tempPlay" value="<%=resource.srcStr("script.ads.tempPlay")%>" />                          
<input type="hidden" id="script.ads.addTime" value="<%=resource.srcStr("script.ads.addTime")%>" />                            
<input type="hidden" id="script.ads.setDifferTime" value="<%=resource.srcStr("script.ads.setDifferTime")%>" />                
<input type="hidden" id="script.ads.playDifferTime" value="<%=resource.srcStr("script.ads.playDifferTime")%>" />              
<input type="hidden" id="script.ads.playStartDate" value="<%=resource.srcStr("script.ads.playStartDate")%>" />                
<input type="hidden" id="script.ads.playEndDate" value="<%=resource.srcStr("script.ads.playEndDate")%>" />                    
<input type="hidden" id="Main.begin_time" value="<%=resource.srcStr("Main.begin_time")%>" />                                
<input type="hidden" id="Main.hour" value="<%=resource.srcStr("Main.hour")%>" />                                          
<input type="hidden" id="Main.min" value="<%=resource.srcStr("Main.min")%>" />                                      
<input type="hidden" id="Main.sec" value="<%=resource.srcStr("Main.sec")%>" />                                      
<input type="hidden" id="script.stopTime" value="<%=resource.srcStr("script.stopTime")%>" />                                  
<input type="hidden" id="script.ads.setDate" value="<%=resource.srcStr("script.ads.setDate")%>" />                            
<input type="hidden" id="Version.notice_text" value="<%=resource.srcStr("Version.notice_text")%>" />       
<input type="hidden" id="Version.announcement" value="<%=resource.srcStr("Version.announcement")%>" />       
<input type="hidden" id="script.ads.rollIntervel" value="<%=resource.srcStr("script.ads.rollIntervel")%>" />                  
<input type="hidden" id="script.ads.increaseIntervel" value="<%=resource.srcStr("script.ads.increaseIntervel")%>" />          
<input type="hidden" id="script.ads.decreaseIntervel" value="<%=resource.srcStr("script.ads.decreaseIntervel")%>" />          
<input type="hidden" id="script.ads.msecend" value="<%=resource.srcStr("script.ads.msecend")%>" />                            
<input type="hidden" id="script.ads.color" value="<%=resource.srcStr("script.ads.color")%>" />                                
<input type="hidden" id="script.ads.click" value="<%=resource.srcStr("script.ads.click")%>" />                                
<input type="hidden" id="System.set" value="<%=resource.srcStr("System.set")%>" />                            
<input type="hidden" id="script.ads.font" value="<%=resource.srcStr("script.ads.font")%>" />                                  
<input type="hidden" id="script.ads.font6" value="<%=resource.srcStr("script.ads.font6")%>" />                                
<input type="hidden" id="script.ads.font5" value="<%=resource.srcStr("script.ads.font5")%>" />                                
<input type="hidden" id="System.black" value="<%=resource.srcStr("System.black")%>" />                                
<input type="hidden" id="script.ads.font3" value="<%=resource.srcStr("script.ads.font3")%>" />                                
<input type="hidden" id="script.ads.font2" value="<%=resource.srcStr("script.ads.font2")%>" />                                
<input type="hidden" id="script.ads.font1" value="<%=resource.srcStr("script.ads.font1")%>" />                                
<input type="hidden" id="script.ads.txtSize" value="<%=resource.srcStr("script.ads.txtSize")%>" />                            
<input type="hidden" id="script.txtContent" value="<%=resource.srcStr("script.txtContent")%>" />                              
<input type="hidden" id="script.announcement" value="<%=resource.srcStr("script.announcement")%>" />                              
<input type="hidden" id="script.ads.textNoticeHere" value="<%=resource.srcStr("script.ads.textNoticeHere")%>" />              
<input type="hidden" id="script.content" value="<%=resource.srcStr("script.content")%>" />                                    
<input type="hidden" id="script.accessory" value="<%=resource.srcStr("script.accessory")%>" />                                
<input type="hidden" id="script.playTime" value="<%=resource.srcStr("script.playTime")%>" />                                  
<input type="hidden" id="script.ads.invalidNumber" value="<%=resource.srcStr("script.ads.invalidNumber")%>" />                
<input type="hidden" id="script.ads.adsLimit" value="<%=resource.srcStr("script.ads.adsLimit")%>" />                          
<input type="hidden" id="script.ads.notNumber" value="<%=resource.srcStr("script.ads.notNumber")%>" />                        
<input type="hidden" id="script.ads.findCounterpart" value="<%=resource.srcStr("script.ads.findCounterpart")%>" />            
<input type="hidden" id="Main.delete" value="<%=resource.srcStr("Main.delete")%>" />                                            
<input type="hidden" id="script.ads.timeInputEmpty" value="<%=resource.srcStr("script.ads.timeInputEmpty")%>" />              
<input type="hidden" id="script.ads.timeInputNumber" value="<%=resource.srcStr("script.ads.timeInputNumber")%>" />            
<input type="hidden" id="script.ads.adsInMinute" value="<%=resource.srcStr("script.ads.adsInMinute")%>" />                    
<input type="hidden" id="script.ads.selectStartDate" value="<%=resource.srcStr("script.ads.selectStartDate")%>" />            
<input type="hidden" id="script.ads.selectEndDate" value="<%=resource.srcStr("script.ads.selectEndDate")%>" />                
<input type="hidden" id="script.ads.endDateError" value="<%=resource.srcStr("script.ads.endDateError")%>" />                  
<input type="hidden" id="script.ads.startDateError" value="<%=resource.srcStr("script.ads.startDateError")%>" />              
<input type="hidden" id="script.ads.selectValidFile" value="<%=resource.srcStr("script.ads.selectValidFile")%>" />            
<input type="hidden" id="script.canNotDecrease" value="<%=resource.srcStr("script.canNotDecrease")%>" />                      
<input type="hidden" id="script.ads.noValidAds" value="<%=resource.srcStr("script.ads.noValidAds")%>" />                      
<input type="hidden" id="script.ads.noAds" value="<%=resource.srcStr("script.ads.noAds")%>" />                                
<input type="hidden" id="script.ads.selectValidAds" value="<%=resource.srcStr("script.ads.selectValidAds")%>" />              
<input type="hidden" id="script.ads.selectAccessory" value="<%=resource.srcStr("script.ads.selectAccessory")%>" />            
<input type="hidden" id="script.ads.startEndTimeError" value="<%=resource.srcStr("script.ads.startEndTimeError")%>" />        
<input type="hidden" id="script.ads.contentTxtLengthLimit" value="<%=resource.srcStr("script.ads.contentTxtLengthLimit")%>" />
<input type="hidden" id="script.ads.contentTxtError" value="<%=resource.srcStr("script.ads.contentTxtError")%>" />            
<input type="hidden" id="script.IntervelError" value="<%=resource.srcStr("script.IntervelError")%>" />                        
<input type="hidden" id="script.inputPlayTimeError" value="<%=resource.srcStr("script.inputPlayTimeError")%>" />              
<input type="hidden" id="script.adsStartTimeEndTime" value="<%=resource.srcStr("script.adsStartTimeEndTime")%>" />            
<input type="hidden" id="script.adsTimeInputError" value="<%=resource.srcStr("script.adsTimeInputError")%>" />                
<input type="hidden" id="script.ads.adsDescLengthLimit" value="<%=resource.srcStr("script.ads.adsDescLengthLimit")%>" />      
<input type="hidden" id="script.ads.invalidContent" value="<%=resource.srcStr("script.ads.invalidContent")%>" />              
<input type="hidden" id="script.ads.validValue" value="<%=resource.srcStr("script.ads.validValue")%>" />                      
<input type="hidden" id="script.ads.selectNo" value="<%=resource.srcStr("script.ads.selectNo")%>" />                          
<input type="hidden" id="Main.the" value="<%=resource.srcStr("Main.the")%>" />                                              
<input type="hidden" id="script.ads.supportedFiles" value="<%=resource.srcStr("script.ads.supportedFiles")%>" />              
<input type="hidden" id="script.ads.ads" value="<%=resource.srcStr("script.ads.ads")%>" />                                    
<input type="hidden" id="script.ads.horseLight" value="<%=resource.srcStr("script.ads.horseLight")%>" />                      
<input type="hidden" id="script.ads.durationNo" value="<%=resource.srcStr("script.ads.durationNo")%>" />                      